server:
  port: 9999
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@ftss9364.synology.me:49154:XE
    username: douzon
    password: 1234
  messages:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org.springframework: DEBUG
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.foresther.www

springboot:
  jwt:
    secret: mySecretKey